# test
site_name: TP de Big Data
copyright: 'Copyright ©2020 Stéphane Derrode'
repo_url: https://github.com/SDerrode/TP_BigData_ECC
theme:
    name: readthedocs
    language: fr
    nav_style: dark
    hljs_languages:
        - python
        - shell
nav:
    - Home: 'README.md'
    - Template_FS: 'Template_FS/README.md'
    - TP1: 'TP1/README.md'
    - TP2: 'TP2/README.md'
    - TP3: 'TP3/README.md'
    - git: 
        - 'tuto-git-gitlab/tuto-git-gitlab.md'
        - 'tuto-git-gitlab/git-commande.md'
    - About: 'about.md'

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - toc
